# 使用 NVIDIA CUDA 基礎映像
FROM nvidia/cuda:11.8.0-devel-ubuntu20.04 as cuda-base

# 設定環境變量以使用 CUDA 和 cuDNN
# path加入/usr/local/cuda/bin
ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"

# 設定非交互式前端，以避免一些警告
ENV DEBIAN_FRONTEND=noninteractive

# 安裝您需要的任何額外依賴
RUN apt-get update && apt-get install -y --no-install-recommends \
    # 編輯器、編譯、連結C/C++程式
    build-essential \   
    # C語言、C++語言編譯器
    gcc g++ \
    # Python3開發庫，用於編譯Python
    libpython3-dev \
    # 從網路上下載文件
    wget curl \
    # 版本控制
    git \
    # 監控系統運行狀態
    htop \
    # OpenGL，用於圖形渲染
    libgl1 libglib2.0-0 \
    # X11圖形系統
    libsm6 \
    # GnuPG，用於加密、簽名和密鑰管理
    gnupg \
    # 壓縮、解壓縮
    zip \
    # USB
    libusb-1.0-0

# 安裝 Python 3.8
RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y \
    python3.8 \
    python3.8-venv \
    python3.8-dev \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
RUN ln -s /usr/bin/python3 /usr/bin/python
# 更新 pip
RUN python3 -m pip install --upgrade pip wheel

# 安装 PyTorch, TorchVision 和 Torchaudio
# 直接去複製安裝該版本的指令
# 指令中最好加入 --no-chahe-dir
# RUN pip3 install --no-cache-dir torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118

# 定義工作目錄 -> 開啟container的預設目錄
WORKDIR /workspace

# YOLOv8相關要另外安裝，先mount進container後再安裝

# 指定容器啟動時執行的命令
CMD ["/bin/bash"]